### ISSUE TITLE
Unable to properly handle special characters in RTMI damage description

### ISSUE THREAD

**Issue by gchan-trailcon** [GCSO2/D3STESTING#211]
Under UAT
The RTMI # 30537
The tire description should be “TIRE FLAT SPOTTED” with all the non-alphabet characters at the end.  
And the label “Status” for L/S Tires is wrong.

RTMI# 30540
Same issue in the Inspection Points tab.  The description is not correctly displayed when there are some special characters.

D3S team said it is fixed.  I will retest again.

**Comment by gchan-trailcon** [comment]
Please refer to RTMI 30540 inbound in UAT

![capture1](https://cloud.githubusercontent.com/assets/6808323/10196509/3b1c6f98-6761-11e5-8fb5-e2a59a9ef72c.GIF)

![capture2](https://cloud.githubusercontent.com/assets/6808323/10196479/0fbfb4ae-6761-11e5-864c-4c3fde5ffa21.GIF)

Please check.  Thanks

**Comment by d3ssupport** [comment]
Oky gary let us check.


Sent from my Samsung device


-------- Original message --------

**Comment by d3ssupport** [comment]
Hello Gary,

 

Below issues are fixed now. Please verify in UAT Environment.

 

Thanks

**Comment by gchan-trailcon** [comment]
Hi D3S team,
Please see RTMI 30547.  The damage description in 1.1 is not complete.  4.1 is wrong again.  You can see the trailer condition tab to see the original data.

**Comment by d3sqa** [comment]
Issue fixed now. Please verify at UAT Environment
