### ISSUE TITLE
RTMI Testing: If trailer has no reefer, gray out the Reefer Billing Type

### ISSUE THREAD

**Issue by gchan-trailcon** [GCSO2/D3STESTING#212]
If trailer has no reefer, please gray out the Reefer Billing Type field
For example: RTMI 30540 in UAT

![reeferbillingtype](https://cloud.githubusercontent.com/assets/6808323/10166629/efeb42a2-6692-11e5-92e8-a5dc67dc632c.jpg)

**Comment by d3ssupport** [comment]
Ok we will gray out. Thanks


Sent from my Samsung device


-------- Original message --------

**Comment by d3sqa** [comment]
Done. Ready to test in UAT Environment
