### ISSUE TITLE
RTMI Testing: Approval not transferred to EMDECS TEST

### ISSUE THREAD

**Issue by gchan-trailcon** [GCSO2/D3STESTING#213]
In UAT
RTMI 30540 has been outbound approved in D3S.  But it is not shown to be transferred to EMDECS TEST.
Is the UAT connected to the EMDECS TEST to transfer RTMI?
Thanks

**Comment by d3ssupport** [comment]
Hi Gary.. 

Let me check connectivity with EMDECS. Thanks



Sent from my Samsung Galaxy smartphone.

In UAT RTMI 30540 has been outbound approved in D3S. But it is not shown to be transferred to EMDECS TEST. Is the UAT connected to the EMDECS TEST to transfer RTMI? Thanks —Reply to this email directly or view it on GitHub.

**Comment by d3ssupport** [comment]
Hi Garry. 

UAT Connected to EMDECS.. Can u plz check it now. 


THANKS



Sent from my Samsung Galaxy smartphone.

In UAT RTMI 30540 has been outbound approved in D3S. But it is not shown to be transferred to EMDECS TEST. Is the UAT connected to the EMDECS TEST to transfer RTMI? Thanks —Reply to this email directly or view it on GitHub.

**Comment by gchan-trailcon** [comment]
Hi support,
Would you please roll back the status of RTMI 30540 to outbound Completed?  So I can reapprove to EMDECS TEST? Thanks

**Comment by d3ssupport** [comment]
Ok we will change it.. 



Sent from my Samsung Galaxy smartphone.

Hi support, Would you please roll back the status of RTMI 30540 to outbound Completed? So I can reapprove to EMDECS TEST? Thanks —Reply to this email directly or view it on GitHub.

**Comment by d3ssupport** [comment]
Done. Status changed

Sent from my Samsung device


-------- Original message --------

**Comment by gchan-trailcon** [comment]
Passed test
