### ISSUE TITLE
RTMI Search not showing customer account #

### ISSUE THREAD

**Issue by gchan-trailcon** [GCSO2/D3STESTING#214]
Refer to issue 206: "Please add Customer Account # (code) to the RTMI Search Screen"
When searching for RTMI in the RTMI Listing screen, the "Customer Account #" does not actually shows the customer.  In this case, it is "DOL100".

![rtmi](https://cloud.githubusercontent.com/assets/6808323/10702096/82e0646a-7995-11e5-915f-6451fab170f1.JPG)

**Comment by d3sqa** [comment]
Done. Ready to test in UAT Environment

**Comment by gchan-trailcon** [comment]
Test passed.  Thanks
